export const firstPage = document.querySelector(".first-page ");
export const secondPage = document.querySelector(".second-page ");
export const backBtn = document.querySelector(".back-botton");
export const password = document.querySelector(".password-input");
export const email = document.querySelector(".email-input");
export const signinBtn = document.querySelector(".sign-in");
export const eye = document.querySelector(".eye");
export const form = document.querySelector(".sign-in-form");
export const passwordAlert = document.querySelector(".invalid-password");
